# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Create dev ipa"
  lane :build_beta_dev do
  enable_automatic_code_signing
  increment_build_number
  gym(scheme: "Debug")
  end

desc "Upload dev to Firebase"
lane :upload_firebase_dev do
firebase_app_distribution(
ipa_path: ENV["IPA_PATH"],
app: ENV["FIREBASE_APP_ID"],
firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
groups: "",
release_notes: "<RELEASE_NOTES>"
)
end

desc "clean"
     lane :clean do
     clear_derived_data(derived_data_path: "./fastlane/builds/")
end

desc "build and upload dev to firebase"
lane :do_everything_dev do
     clean
     build_beta_dev
     upload_firebase_dev
end

end
